When removing a user, I can select a replacement #266
effektif/user-docs pull request #268
Opened 2017-07-04 09:19 UTC by Lengocduong

2017-07-04 11:28 UTC, SilentGert requested changes

2017-07-04 11:28 UTC, SilentGert commented on docs/_locale/de/LC_MESSAGES/settings.po
> +msgid "in workflows: owner, assignments, candidates, default values for form fields, transition conditions, JavaScript test values, access"
Do you usually call it `access` or `access rights`. The same in german `Zugriff` vs. `Zugriffsrechte`.

2017-07-04 11:28 UTC, SilentGert commented on docs/settings.rst
> +but not automatically inherits all rolls or rights of the deleted user.
`rolls` should be `roles`
I'm a bit confused by the last part:
> but not automatically inherits all rolls or rights of the deleted user.

What exactly would be roles and rights?
It is correct that if you use roles within a case for tasks, the value there isn't changed. However, we adjust access rights in cases and tasks where necessary.

Another thing to mention would be the assignment for closed tasks is not changed for audit reasons.

2017-07-04 11:28 UTC, SilentGert commented on docs/settings.rst
> +* in workflows: owner, assignments, candidates, default values for form fields, transition conditions, JavaScript test values, access
As mentioned before, I would extend `access` to `access rights`

2017-07-05 08:46 UTC, Lengocduong commented on docs/_locale/de/LC_MESSAGES/settings.po
> +msgid "in workflows: owner, assignments, candidates, default values for form fields, transition conditions, JavaScript test values, access"
I think, access rights is more precise

2017-07-05 08:52 UTC, Lengocduong commented on docs/settings.rst
> +but not automatically inherits all rolls or rights of the deleted user.
I 'd like to point out that the substitute will merely have exactly the necessary access right to complete the tasks, but will not automatically inherit all rights of his predecessor.

2017-07-05 16:21 UTC, SilentGert commented on docs/settings.rst
> +but not automatically inherits all rolls or rights of the deleted user.
If rights means access rights, it's not correct. The substitute will inherit the access rights for open tasks and cases. If rights means group memberships then that's correct, they are not transferred.

2017-07-06 11:06 UTC, SilentGert approved these changes

2017-07-07 05:48 UTC, Lengocduong commented
@SilentGert : Merge please :-) !

2017-07-07 06:39 UTC, SilentGert commented
What about the failing travis checks? Do you ignore them?

2017-07-07 09:21 UTC, TimKam commented
I'll have a look at the failing checks.

2017-07-07 17:07 UTC, TimKam approved these changes

2017-07-07 17:08 UTC, merged