Multi-user task manual decisions #267
effektif/user-docs pull request #282
Opened 2017-07-25 14:04 UTC by Lengocduong

2017-07-25 15:44 UTC, SilentGert commented on docs/_locale/de/LC_MESSAGES/action-types.po
> +msgstr "Alle Nutzer haben diese Option ausgewählt."
What about the markdown highlighting here: `*...*`

2017-07-25 19:07 UTC, TimKam requested changes
One detail, plus Gert's comment. Otherwise, 👍

2017-07-25 19:07 UTC, TimKam commented on docs/include_action-types/multi-user-task.rst
> +If an exclusive gateway follows a multi-user task, you can configure the buttons, which reflect the possible decisions to this gateway.
*which* -> *that*

2017-07-25 19:08 UTC, TimKam commented on docs/include_action-types/multi-user-task.rst
> +Select the decision type 'Manual' for the exclusive gateway. Then choose the decision option from the dropdown menu:
I forgot: *dropdown* -> *drop-down*

2017-07-26 10:55 UTC, TimKam approved these changes

2017-07-26 11:23 UTC, merged