Limit the number of users who can create new workflows #285
effektif/user-docs pull request #286
Opened 2017-07-31 10:27 UTC by Lengocduong

2017-07-31 11:51 UTC, Lengocduong commented
@SilentGert : from which release on this feature will be available (I need to add it to the docs).

2017-07-31 11:54 UTC, TimKam requested changes

2017-07-31 11:54 UTC, TimKam commented on docs/_locale/de/LC_MESSAGES/settings.po
> +msgid "*Process creation* You can activate this option to configure which group of users can create processes."
Isn't it possible to assign multiple group*s*? Also, I suggest linking to settings.html#groups

2017-07-31 11:57 UTC, Lengocduong commented on docs/_locale/de/LC_MESSAGES/settings.po
> +msgid "*Process creation* You can activate this option to configure which group of users can create processes."
I tested that, it was not possible. 
@SilentGert :  is it intended to specify multiple groups?

2017-07-31 12:07 UTC, TimKam commented on docs/_locale/de/LC_MESSAGES/settings.po
> +msgid "*Process creation* You can activate this option to configure which group of users can create processes."
Because Gert is on vacation, let's ask @mavo :-)

2017-07-31 12:51 UTC, SilentGert commented on docs/_locale/de/LC_MESSAGES/settings.po
> +msgid "*Process creation* You can activate this option to configure which group of users can create processes."
No, the intention is to have exactly one group for that mechanism.

2017-07-31 12:51 UTC, SilentGert commented
@Lengocduong It will be available with the next release 3.34.

2017-07-31 13:10 UTC, TimKam commented on docs/_locale/de/LC_MESSAGES/settings.po
> +msgid "*Process creation* You can activate this option to configure which group of users can create processes."
Ok, then we should update the screenshots and call the group "Process creators" or something

2017-08-02 12:32 UTC, SilentGert reviewed
I think it would be good, if on your image the option is actually selected (yes is chosen)

2017-08-02 12:38 UTC, TimKam approved these changes

2017-08-02 12:47 UTC, merged